// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbxgdgpmvobmrdlibauf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRieGdkZ3Btdm9ibXJkbGliYXVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNTE2NzYsImV4cCI6MjA1NzcyNzY3Nn0.--J_mpKfNdwOC6BX6Qx-AVP_WDCytF0Xhq7uj3OwnZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);